version: '3.7'

services:

  # Database
  db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      
    
  # The application
  app:
    build:
      context: .
    image: &app app
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
    env_file:
      - .env
    command: >
      sh -c 'python manage.py makemigrations && python manage.py migrate && python manage.py loaddata recipebook/fixtures/initial_data.json
      && watchmedo auto-restart --directory=./ --pattern=*.py --recursive -- python manage.py runserver 0.0.0.0:8000'
    links:
      - db
    depends_on:
      - db
