# Generated by Django 4.0.2 on 2022-02-07 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Ингредиент',
                'verbose_name_plural': 'Ингредиенты',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('poster', models.ImageField(upload_to='recipe_posters/', verbose_name='Главное фото')),
                ('url', models.SlugField(max_length=100)),
                ('draft', models.BooleanField(default=False, verbose_name='Черновик')),
                ('ingredients', models.ManyToManyField(related_name='recipe_ingredients', to='recipebook.Ingredient', verbose_name='Ингрединеты')),
            ],
            options={
                'verbose_name': 'Рецепт',
                'verbose_name_plural': 'Рецепты',
            },
        ),
        migrations.CreateModel(
            name='RecipeImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Название')),
                ('image', models.ImageField(upload_to='recipe_images/', verbose_name='Фото')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipeimages', to='recipebook.recipe', verbose_name='Рецепт')),
            ],
            options={
                'verbose_name': 'Фотография для рецепта',
                'verbose_name_plural': 'Фотографии для рецепта',
            },
        ),
    ]
