# Generated by Django 4.0.2 on 2022-02-07 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipebook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='instruction',
            field=models.TextField(default=1, verbose_name='Инструкция приготовления'),
            preserve_default=False,
        ),
    ]
