# Generated by Django 4.0.2 on 2022-02-09 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipebook', '0003_alter_ingredient_name_alter_recipe_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(to='recipebook.Ingredient', verbose_name='Ингрединеты'),
        ),
        migrations.AlterField(
            model_name='recipeimages',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_images', to='recipebook.recipe', verbose_name='Рецепт'),
        ),
    ]
